version: '3.4'

services:
    run:
        container_name: ql-run
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=development
            #- NODE_ENV=production
            - SERVER_PROTOCOL=${ENV_SERVER_PROTOCOL:-http}
            - SERVER_HOST=${ENV_SERVER_HOST:-localhost}
            - SERVER_PORT=${ENV_SERVER_PORT:-3000}
            - API_PROTOCOL=${ENV_API_PROTOCOL:-http}
            - API_HOST=${ENV_API_HOST:-host.docker.internal}
            - API_PORT=${ENV_API_PORT:-8080}
            #- ASSETS_SERVER=http://static-server
        volumes:
            - ./@types:/usr/src/app/@types
            - ./src:/usr/src/app/src
        ports:
          - 3000:3000
        command: bash -c "npm run dev"
        #command: bash -c "npm start"

    test:
        container_name: ql-test
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=development
        volumes:
            - ./@types:/usr/src/app/@types
            - ./src:/usr/src/app/src
            - ./jest:/usr/src/app/jest
        command: bash -c "npm test && npm run lint"
