version: '3.4'

services:

    #
    #   Starts the service without any dependencies in development mode.
    #
    #   This is great for development. Either set API_HOST
    #   to loggjafarthing.einarvalur.co to use production service
    #
    #   ...or leave it to use API Service running on your local
    #   system.
    #
    run:
        container_name: ql-run
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=development
            - SERVER_PROTOCOL=${ENV_SERVER_PROTOCOL:-http}
            - SERVER_HOST=${ENV_SERVER_HOST:-localhost}
            - SERVER_PORT=${ENV_SERVER_PORT:-3000}
            - API_PROTOCOL=${ENV_API_PROTOCOL:-http}
            - API_HOST=${ENV_API_HOST:-host.docker.internal}
            - API_PORT=${ENV_API_PORT:-8080}
            - IMAGE_SERVER=${ENV_IMAGE_SERVER:-/images}
            #- ASSETS_SERVER=http://static-server
        volumes:
            - ./@types:/usr/src/app/@types
            - ./src:/usr/src/app/src
        ports:
          - 3000:3000
        command: bash -c "npm run dev"

    test:
        container_name: ql-test
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=development
        volumes:
            - ./@types:/usr/src/app/@types
            - ./src:/usr/src/app/src
            - ./jest:/usr/src/app/jest
        command: bash -c "npm test && npm run lint"
